package tweaks.wurm.crafting.thaumcraft;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.api.internal.WeightedRandomLoot;
import thaumcraft.common.config.ConfigBlocks;
import thaumcraft.common.config.ConfigItems;
import thaumic.tinkerer.common.ThaumicTinkerer;
import thaumicenergistics.api.ThEApi;
import thaumicenergistics.registries.ResearchRegistry;
import tweaks.wurm.utils.tfc.TFCFood;
import tweaks.wurm.utils.thaumcraft.InfusionRecipe;
import tweaks.wurm.utils.thaumcraft.Research;
import am2.items.ItemsCommonProxy;
import appeng.api.AEApi;
import cofh.thermalfoundation.item.TFItems;

import com.bioxx.tfc.api.TFCItems;
import com.rwtema.extrautils.ExtraUtils;

import cpw.mods.fml.common.registry.GameRegistry;

public class InfusionThaumcraft {
	
	public static void addRecipes() {
		
		 new InfusionRecipe("ROD_reed", new ItemStack(ConfigItems.itemWandRod,1,5),2,new AspectList().add(Aspect.WATER,20).add(Aspect.AIR,20).add(Aspect.MAGIC,20),new ItemStack(TFCItems.Reeds), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("ROD_quartz", new ItemStack(ConfigItems.itemWandRod,1,4),2,new AspectList().add(Aspect.CRYSTAL,20).add(Aspect.AIR,20).add(Aspect.MAGIC,20),new ItemStack(Items.quartz), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("ROD_obsidian", new ItemStack(ConfigItems.itemWandRod,1,1),2,new AspectList().add(Aspect.DARKNESS,20).add(Aspect.AIR,20).add(Aspect.MAGIC,20),new ItemStack(Blocks.obsidian), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("ROD_blaze", new ItemStack(ConfigItems.itemWandRod,1,6),2,new AspectList().add(Aspect.FIRE,20).add(Aspect.AIR,20).add(Aspect.MAGIC,20),new ItemStack(Items.blaze_rod), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("ROD_ice", new ItemStack(ConfigItems.itemWandRod,1,3),2,new AspectList().add(Aspect.COLD,20).add(Aspect.AIR,20).add(Aspect.MAGIC,20),new ItemStack(Blocks.ice), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("ROD_bone", new ItemStack(ConfigItems.itemWandRod,1,7),2,new AspectList().add(Aspect.DEATH,20).add(Aspect.AIR,20).add(Aspect.MAGIC,20),new ItemStack(Items.bone), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("ROD_silverwood", new ItemStack(ConfigItems.itemWandRod,1,2),2,new AspectList().add(Aspect.AIR,20).add(Aspect.MAGIC,40),new ItemStack(ConfigBlocks.blockMagicalLog,1,1), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ItemsCommonProxy.essence,1,10));
		 new InfusionRecipe("NODESTABILIZERADV", new ItemStack(ConfigBlocks.blockStoneDevice,1,10),8, new AspectList().add(Aspect.AURA,20).add(Aspect.ORDER,15).add(Aspect.ENERGY,20).add(Aspect.ENERGY,40),new ItemStack(ConfigBlocks.blockStoneDevice,1,9), new ItemStack(tweaks.wurm.items.ModBlocks.CompressedRedstoneBlock),new ItemStack(ConfigItems.itemResource,1,1), new ItemStack(tweaks.wurm.items.ModBlocks.CompressedRedstoneBlock), new ItemStack(ConfigItems.itemResource,1,0), new ItemStack(ConfigItems.itemResource,1,0),new ItemStack(tweaks.wurm.items.ModBlocks.CompressedRedstoneBlock), new ItemStack(ConfigItems.itemResource,1,1), new ItemStack(tweaks.wurm.items.ModBlocks.CompressedRedstoneBlock));
		 new InfusionRecipe("FOCUSWARDING", new ItemStack(ConfigItems.itemFocusWarding), 12, new AspectList().add(Aspect.AURA,20).add(Aspect.MAGIC,20).add(Aspect.EARTH,25).add(Aspect.ARMOR,25), new ItemStack(Items.nether_star), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(Items.quartz), new ItemStack(Items.quartz));
		 new InfusionRecipe("FOCUSPORTABLEHOLE", new ItemStack(ConfigItems.itemFocusPortableHole), 6, new AspectList().add(Aspect.AURA,20).add(Aspect.MAGIC,20).add(Aspect.EARTH,25).add(Aspect.ARMOR,25), new ItemStack(Items.ender_pearl), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(Items.quartz), new ItemStack(Items.quartz));
		 new InfusionRecipe("WANDPED", new ItemStack(ConfigBlocks.blockStoneDevice,1,5),4, new AspectList().add(Aspect.AURA,20).add(Aspect.MAGIC,20).add(Aspect.CRAFT,20), new ItemStack(ConfigBlocks.blockStoneDevice,1,1), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore));
		 new InfusionRecipe("WANDPEDFOC", new ItemStack(ConfigBlocks.blockStoneDevice,1,8),8, new AspectList().add(Aspect.MAGIC,20).add(Aspect.ELDRITCH,50), new ItemStack(Items.comparator), new ItemStack(Items.quartz), new ItemStack(Items.quartz), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("FOCUSHELLBAT", new ItemStack(ConfigItems.itemFocusHellbat),15, new AspectList().add(Aspect.DARKNESS,64).add(Aspect.DEATH,64).add(Aspect.ARMOR,64),new ItemStack(Items.magma_cream), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(ExtraUtils.cobblestoneCompr,1,6));
		 new InfusionRecipe("BOOTSTRAVELLER", new ItemStack(ConfigItems.itemBootsTraveller),6, new AspectList().add(Aspect.FLIGHT,15).add(Aspect.MOTION,20), new ItemStack(TFCItems.RedSteelBoots,1,0), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(TFCItems.RedSteelSheet), new ItemStack(TFCItems.BlueSteelSheet), TFCFood.getFood(TFCItems.fishRaw, 160f));
		 new InfusionRecipe("JARBRAIN", new ItemStack(ConfigBlocks.blockJar,1,1),12, new AspectList().add(Aspect.BEAST,20).add(Aspect.AURA,20), new ItemStack(ConfigBlocks.blockJar,1,0), new ItemStack(TFCItems.RedSteelSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(Items.rotten_flesh));
		 new InfusionRecipe("MIRROR", new ItemStack(ConfigBlocks.blockMirror,1,0),4, new AspectList().add(Aspect.MAGIC,25).add(Aspect.MECHANISM,20), new ItemStack(ConfigItems.itemResource,1,10), new ItemStack(TFCItems.GoldSheet), new ItemStack(TFCItems.GoldSheet), new ItemStack(Items.ender_pearl), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("MIRRORESSENTIA", new ItemStack(ConfigBlocks.blockMirror,1,6),6, new AspectList().add(Aspect.MAGIC,20).add(Aspect.AURA,20), new ItemStack(ConfigItems.itemResource,1,10), new ItemStack(TFCItems.RedSteelSheet), new ItemStack(TFCItems.RedSteelSheet),new ItemStack(TFCItems.BlueSteelSheet));
		 new InfusionRecipe("MIRRORHAND", new ItemStack(ConfigItems.itemHandMirror),4, new AspectList().add(Aspect.MAGIC,20), new ItemStack(ConfigBlocks.blockMirror), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("HOVERHARNESS", new ItemStack(ConfigItems.itemHoverHarness),12, new AspectList().add(Aspect.FLIGHT,10).add(Aspect.AIR,10).add(Aspect.ENERGY,20), new ItemStack(TFCItems.RedSteelChestplate), new ItemStack(TFCItems.RedSteelSheet), new ItemStack(TFCItems.BlueSteelSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("HOVERGIRDLE", new ItemStack(ConfigItems.itemGirdleHover),2, new AspectList().add(Aspect.BEAST,10).add(Aspect.GREED,10).add(Aspect.POISON,10).add(Aspect.ENERGY,25), new ItemStack(ConfigItems.itemHoverHarness), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore));
		 new InfusionRecipe("SINSTONE", new ItemStack(ConfigItems.itemCompassStone), 8, new AspectList().add(Aspect.DARKNESS,20).add(Aspect.BEAST,20).add(Aspect.DEATH,20),new ItemStack(Items.flint), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore));
		 new InfusionRecipe("SANITYCHECK", new ItemStack(ConfigItems.itemSanityChecker),16, new AspectList().add(Aspect.DARKNESS,20).add(Aspect.SOUL,20).add(Aspect.MAGIC,20), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(TFCItems.BlueSteelSheet), new ItemStack(TFCItems.RedSteelSheet), new ItemStack(tweaks.wurm.items.ModBlocks.BlackSteelBlock));
		 new InfusionRecipe(ResearchRegistry.ResearchTypes.INFUSIONPROVIDER.getKey(), ThEApi.instance().blocks().InfusionProvider.getStack(),12,new AspectList().add(Aspect.MECHANISM,64).add(Aspect.ORDER,64).add(Aspect.MAGIC,64), AEApi.instance().blocks().blockInterface.stack(1),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(ConfigBlocks.blockEssentiaReservoir), new ItemStack(tweaks.wurm.items.ModBlocks.BlackSteelBlock));
		 new InfusionRecipe(ResearchRegistry.ResearchTypes.ESSENTIAPROVIDER.getKey(), ThEApi.instance().blocks().EssentiaProvider.getStack(),12,new AspectList().add(Aspect.MECHANISM,64).add(Aspect.ORDER,64).add(Aspect.MAGIC,64), AEApi.instance().blocks().blockInterface.stack(1),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(ConfigBlocks.blockEssentiaReservoir), new ItemStack(tweaks.wurm.items.ModBlocks.BlackSteelBlock), new ItemStack(ConfigBlocks.blockTube,1,3), new ItemStack(ConfigBlocks.blockTube,1,3));
		 new InfusionRecipe(ResearchRegistry.ResearchTypes.ARCANEASSEMBLER.getKey(), ThEApi.instance().blocks().ArcaneAssembler.getStack(),20, new AspectList().add(Aspect.MAGIC,256).add(Aspect.MAGIC,128),new ItemStack(AEApi.instance().blocks().blockMolecularAssembler.block()), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("ICHORCLOTH_HELM_GEM", GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothHelmGem", 1), 30,new AspectList().add(Aspect.MAGIC,512).add(Aspect.MIND,128).add(Aspect.ORDER,256).add(Aspect.DARKNESS,64).add(Aspect.ELDRITCH,64).add(Aspect.ARMOR,256), GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothHelm", 1), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(ConfigItems.itemFocusPrimal), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock)); 
		 new InfusionRecipe("FOCUS_SHADOWBEAM", GameRegistry.findItemStack("ThaumicTinkerer", "focusShadowbeam", 1),20, new AspectList().add(Aspect.CRAFT,64).add(Aspect.MAGIC,50).add(Aspect.ARMOR,32).add(Aspect.DARKNESS,64), new ItemStack(ConfigItems.itemFocusShock),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource",1).getItem(),1,0),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource",1).getItem(),1,0),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource",1).getItem(),1,0),new ItemStack(ConfigItems.itemFocusExcavation), new ItemStack(ConfigItems.itemFocusWarding));
		 new InfusionRecipe("ICHOR_POUCH",GameRegistry.findItemStack("ThaumicTinkerer", "ichorPouch", 1),15, new AspectList().add(Aspect.VOID,64).add(Aspect.MAGIC,64).add(Aspect.CLOTH,32), new ItemStack(ConfigItems.itemFocusPouch), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1), TFItems.bucketEnder, new ItemStack(Items.ender_pearl),new ItemStack(ConfigItems.itemFocusPortableHole));
		 new InfusionRecipe("XP_TALISMAN", GameRegistry.findItemStack("ThaumicTinkerer", "xpTalisman", 1),10, new AspectList().add(Aspect.CLOTH,64).add(Aspect.CRAFT,64), new ItemStack(ConfigItems.itemZombieBrain),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("FOCUS_XP_DRAIN", GameRegistry.findItemStack("ThaumicTinkerer", "focusXPDrain",1), 5, new AspectList().add(Aspect.AURA,64).add(Aspect.COLD,64).add(Aspect.MAGIC,64).add(Aspect.UNDEAD,64), new ItemStack(Items.ender_pearl), new ItemStack(Blocks.enchanting_table), GameRegistry.findItemStack("ThaumicTinkerer", "xpTalisman", 1), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(tweaks.wurm.items.ModBlocks.BlueSteelBlock));
		 new InfusionRecipe("ENCHANTER", GameRegistry.findItemStack("ThaumicTinkerer", "enchanter", 1),8, new AspectList().add(Aspect.MAGIC,64).add(Aspect.CLOTH,32).add(Aspect.AURA,16), new ItemStack(Blocks.enchanting_table), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("ICHORCLOTH_LEGS_GEM", GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothLegsGem", 1), 30,new AspectList().add(Aspect.MAGIC,512).add(Aspect.MIND,128).add(Aspect.ORDER,256).add(Aspect.DARKNESS,64).add(Aspect.ELDRITCH,64).add(Aspect.ARMOR,256), GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothLegs", 1), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(ConfigItems.itemFocusPrimal), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock)); 
		 new InfusionRecipe("CAP_thaumium", new ItemStack(ConfigItems.itemWandCap,1,2),4, new AspectList().add(Aspect.MAGIC,32).add(Aspect.ORDER,32), new ItemStack(ConfigItems.itemWandCap,1,6), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet));
		 new InfusionRecipe("ICHORCLOTH_BOOTS_GEM", GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothBootsGem", 1), 30,new AspectList().add(Aspect.MAGIC,512).add(Aspect.MIND,128).add(Aspect.ORDER,256).add(Aspect.DARKNESS,64).add(Aspect.ELDRITCH,64).add(Aspect.ARMOR,256), GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothBoots", 1), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(ConfigItems.itemFocusPrimal), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock)); 
		 new InfusionRecipe("ICHORCLOTH_CHEST_GEM", GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothChestGem", 1), 30,new AspectList().add(Aspect.MAGIC,512).add(Aspect.MIND,128).add(Aspect.ORDER,256).add(Aspect.DARKNESS,64).add(Aspect.ELDRITCH,64).add(Aspect.ARMOR,256), GameRegistry.findItemStack("ThaumicTinkerer", "ichorclothChest", 1), new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(ConfigItems.itemFocusPrimal), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock), new ItemStack(ExtraUtils.bedrockiumBlock)); 
		 new InfusionRecipe("ROD_ICHORCLOTH	", new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,5),4, new AspectList().add(Aspect.AIR,50).add(Aspect.MAGIC,100), new ItemStack(ConfigItems.itemWandRod,1,2), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1), new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,1),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore));
		 new InfusionRecipe("ICHOR", new ItemStack(GameRegistry.findItemStack("ThaumicTinkerer", "kamiResource", 1).getItem(),1,0),2, new AspectList().add(Aspect.MAGIC,128).add(Aspect.ORDER,128).add(Aspect.CLOTH,64), new ItemStack(Items.nether_star), new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.MixedSheet),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore),new ItemStack(tweaks.wurm.items.ModItems.CraftingCore));
		 
	}

	public static void refreshBook() {
		
		Research.RefreshResearch("ROD_reed");
		Research.RefreshResearch("ROD_quartz");
		Research.RefreshResearch("ROD_obsidian");
		Research.RefreshResearch("ROD_blaze");
		Research.RefreshResearch("ROD_ice");
		Research.RefreshResearch("ROD_bone");
		Research.RefreshResearch("ROD_silverwood");
		Research.RefreshResearch("NODESTABILIZERADV");
		Research.RefreshResearch("FOCUSWARDING");
		Research.RefreshResearch("FOCUSPORTABLEHOLE");
		Research.RefreshResearch("WANDPED");
		Research.RefreshResearch("WANDPEDFOC");
		Research.RefreshResearch("FOCUSHELLBAT");
		Research.RefreshResearch("BOOTSTRAVELLER");
		Research.RefreshResearch("JARBRAIN");
		Research.RefreshResearch("ARCANEBORE");
		Research.RefreshResearch("MIRROR");
		Research.RefreshResearch("MIRRORESSENTIA");
		Research.RefreshResearch("MIRRORHAND");
		Research.RefreshResearch("HOVERHARNESS");
		Research.RefreshResearch("HOVERGIRDLE");
		Research.RefreshResearch("SINSTONE");
		Research.RefreshResearch("SANITYCHECK");
		Research.RefreshResearch(ResearchRegistry.ResearchTypes.INFUSIONPROVIDER.getKey());
		Research.RefreshResearch(ResearchRegistry.ResearchTypes.ESSENTIAPROVIDER.getKey());
		Research.RefreshResearch(ResearchRegistry.ResearchTypes.ARCANEASSEMBLER.getKey());
		Research.RefreshResearch("ICHORCLOTH_HELM_GEM");
		Research.RefreshResearch("FOCUS_SHADOWBEAM");
		Research.RefreshResearch("ICHOR_POUCH");
		Research.RefreshResearch("XP_TALISMAN");
		Research.RefreshResearch("FOCUS_XP_DRAIN");
		Research.RefreshResearch("ENCHANTER");
		Research.RefreshResearch("ICHORCLOTH_LEGS_GEM");
		Research.RefreshResearch("CAP_thaumium");
		Research.RefreshResearch("ICHORCLOTH_BOOTS_GEM");
		Research.RefreshResearch("ICHORCLOTH_LEGS_CHEST");
		Research.RefreshResearch("ROD_ICHORCLOTH");
		Research.RefreshResearch("ICHOR");
	}
}