package tweaks.wurm.crafting.te2;

import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.FluidRegistry;
import tweaks.wurm.utils.TE.TERecipes;

import com.bioxx.tfc.api.TFCItems;

public class Crucible {
	
	// molten.*
	public static void addRecipe() {
		
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_iron), FluidRegistry.getFluidStack("molten.wurmwroughtiron", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_iron), FluidRegistry.getFluidStack("molten.wurmwroughtiron", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_iron), FluidRegistry.getFluidStack("molten.wurmwroughtiron", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_copper), FluidRegistry.getFluidStack("molten.wurmcopper", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_copper), FluidRegistry.getFluidStack("molten.wurmcopper", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_copper), FluidRegistry.getFluidStack("molten.wurmcopper", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_gold), FluidRegistry.getFluidStack("molten.wurmgold", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_gold), FluidRegistry.getFluidStack("molten.wurmgold", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_gold), FluidRegistry.getFluidStack("molten.wurmgold", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_platinum), FluidRegistry.getFluidStack("molten.wurmplatinum", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_platinum), FluidRegistry.getFluidStack("molten.wurmplatinum", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_platinum), FluidRegistry.getFluidStack("molten.wurmplatinum", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_tin), FluidRegistry.getFluidStack("molten.wurmtin", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_tin), FluidRegistry.getFluidStack("molten.wurmtin", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_tin), FluidRegistry.getFluidStack("molten.wurmtin", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_lead), FluidRegistry.getFluidStack("molten.wurmlead", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_lead), FluidRegistry.getFluidStack("molten.wurmlead", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_lead), FluidRegistry.getFluidStack("molten.wurmlead", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_bismuth), FluidRegistry.getFluidStack("molten.wurmbismuth", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_bismuth), FluidRegistry.getFluidStack("molten.wurmbismuth", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_bismuth), FluidRegistry.getFluidStack("molten.wurmbismuth", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_nickel), FluidRegistry.getFluidStack("molten.wurmnickel", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_nickel), FluidRegistry.getFluidStack("molten.wurmnickel", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_nickel), FluidRegistry.getFluidStack("molten.wurmnickel", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_zinc), FluidRegistry.getFluidStack("molten.wurmzinc", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_zinc), FluidRegistry.getFluidStack("molten.wurmzinc", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_zinc), FluidRegistry.getFluidStack("molten.wurmzinc", 700));
		TERecipes.addCrucibleRecipe(8000, new ItemStack(tweaks.wurm.items.ModItems.aCred_silver), FluidRegistry.getFluidStack("molten.wurmsilver", 300));
		TERecipes.addCrucibleRecipe(9000, new ItemStack(tweaks.wurm.items.ModItems.bCred_silver), FluidRegistry.getFluidStack("molten.wurmsilver", 500));
		TERecipes.addCrucibleRecipe(10000, new ItemStack(tweaks.wurm.items.ModItems.cCred_silver), FluidRegistry.getFluidStack("molten.wurmsilver", 700));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthIngot), FluidRegistry.getFluidStack("molten.wurmbismuth", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthIngot2x), FluidRegistry.getFluidStack("molten.wurmbismuth", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthSheet), FluidRegistry.getFluidStack("molten.wurmbismuth", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthSheet2x), FluidRegistry.getFluidStack("molten.wurmbismuth", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.TinIngot), FluidRegistry.getFluidStack("molten.wurmtin", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.TinIngot2x), FluidRegistry.getFluidStack("molten.wurmtin", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.TinSheet), FluidRegistry.getFluidStack("molten.wurmtin", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.TinSheet2x), FluidRegistry.getFluidStack("molten.wurmtin", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.ZincIngot), FluidRegistry.getFluidStack("molten.wurmzinc", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.ZincIngot2x), FluidRegistry.getFluidStack("molten.wurmzinc", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.ZincSheet), FluidRegistry.getFluidStack("molten.wurmzinc", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.ZincSheet2x), FluidRegistry.getFluidStack("molten.wurmzinc", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.CopperIngot), FluidRegistry.getFluidStack("molten.wurmcopper", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.CopperIngot2x), FluidRegistry.getFluidStack("molten.wurmcopper", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.CopperSheet), FluidRegistry.getFluidStack("molten.wurmcopper", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.CopperSheet2x), FluidRegistry.getFluidStack("molten.wurmcopper", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BronzeIngot), FluidRegistry.getFluidStack("molten.wurmbronze", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BronzeIngot2x), FluidRegistry.getFluidStack("molten.wurmbronze", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BronzeSheet), FluidRegistry.getFluidStack("molten.wurmbronze", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BronzeSheet2x), FluidRegistry.getFluidStack("molten.wurmbronze", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthBronzeIngot), FluidRegistry.getFluidStack("molten.wurmbismuthbronze", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthBronzeIngot2x), FluidRegistry.getFluidStack("molten.wurmbismuthbronze", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthBronzeSheet), FluidRegistry.getFluidStack("molten.wurmbismuthbronze", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BismuthBronzeSheet2x), FluidRegistry.getFluidStack("molten.wurmbismuthbronze", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackBronzeIngot), FluidRegistry.getFluidStack("molten.wurmblackbronze", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackBronzeIngot2x), FluidRegistry.getFluidStack("molten.wurmblackbronze", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackBronzeSheet), FluidRegistry.getFluidStack("molten.wurmblackbronze", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackBronzeSheet2x), FluidRegistry.getFluidStack("molten.wurmblackbronze", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BrassIngot), FluidRegistry.getFluidStack("molten.wurmbrass", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BrassIngot2x), FluidRegistry.getFluidStack("molten.wurmbrass", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BrassSheet), FluidRegistry.getFluidStack("molten.wurmbrass", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BrassSheet2x), FluidRegistry.getFluidStack("molten.wurmbrass", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.LeadIngot), FluidRegistry.getFluidStack("molten.wurmlead", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.LeadIngot2x), FluidRegistry.getFluidStack("molten.wurmlead", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.LeadSheet), FluidRegistry.getFluidStack("molten.wurmlead", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.LeadSheet2x), FluidRegistry.getFluidStack("molten.wurmlead", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.GoldIngot), FluidRegistry.getFluidStack("molten.wurmgold", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.GoldIngot2x), FluidRegistry.getFluidStack("molten.wurmgold", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.GoldSheet), FluidRegistry.getFluidStack("molten.wurmgold", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.GoldSheet2x), FluidRegistry.getFluidStack("molten.wurmgold", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RoseGoldIngot), FluidRegistry.getFluidStack("molten.wurmrosegold", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RoseGoldIngot2x), FluidRegistry.getFluidStack("molten.wurmrosegold", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RoseGoldSheet), FluidRegistry.getFluidStack("molten.wurmrosegold", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RoseGoldSheet2x), FluidRegistry.getFluidStack("molten.wurmrosegold", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SilverIngot), FluidRegistry.getFluidStack("molten.wurmsilver", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SilverIngot2x), FluidRegistry.getFluidStack("molten.wurmsilver", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SilverSheet), FluidRegistry.getFluidStack("molten.wurmsilver", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SilverSheet2x), FluidRegistry.getFluidStack("molten.wurmsilver", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SterlingSilverIngot), FluidRegistry.getFluidStack("molten.wurmsterlingsilver", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SterlingSilverIngot2x), FluidRegistry.getFluidStack("molten.wurmsterlingsilver", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SterlingSilverSheet), FluidRegistry.getFluidStack("molten.wurmsterlingsilver", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SterlingSilverSheet2x), FluidRegistry.getFluidStack("molten.wurmsterlingsilver", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PlatinumIngot), FluidRegistry.getFluidStack("molten.wurmplatinum", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PlatinumIngot2x), FluidRegistry.getFluidStack("molten.wurmplatinum", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PlatinumSheet), FluidRegistry.getFluidStack("molten.wurmplatinum", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PlatinumSheet2x), FluidRegistry.getFluidStack("molten.wurmplatinum", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.WroughtIronIngot), FluidRegistry.getFluidStack("molten.wurmwroughtiron", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.WroughtIronIngot2x), FluidRegistry.getFluidStack("molten.wurmwroughtiron", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.WroughtIronSheet), FluidRegistry.getFluidStack("molten.wurmwroughtiron", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.WroughtIronSheet2x), FluidRegistry.getFluidStack("molten.wroguhtiron", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.NickelIngot), FluidRegistry.getFluidStack("molten.wurmnickel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.NickelIngot2x), FluidRegistry.getFluidStack("molten.wurmnickel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.NickelSheet), FluidRegistry.getFluidStack("molten.wurmnickel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.NickelSheet2x), FluidRegistry.getFluidStack("molten.wurmnickel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PigIronIngot), FluidRegistry.getFluidStack("molten.wurmpigiron", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PigIronIngot2x), FluidRegistry.getFluidStack("molten.wurmpigiron", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PigIronSheet), FluidRegistry.getFluidStack("molten.wurmpigiron", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.PigIronSheet2x), FluidRegistry.getFluidStack("molten.wurmpigiron", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SteelIngot), FluidRegistry.getFluidStack("molten.wurmsteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SteelIngot2x), FluidRegistry.getFluidStack("molten.wurmsteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SteelSheet), FluidRegistry.getFluidStack("molten.wurmsteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.SteelSheet2x), FluidRegistry.getFluidStack("molten.wurmsteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackSteelIngot), FluidRegistry.getFluidStack("molten.wurmblacksteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackSteelIngot2x), FluidRegistry.getFluidStack("molten.wurmblacksteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackSteelSheet), FluidRegistry.getFluidStack("molten.wurmblacksteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlackSteelSheet2x), FluidRegistry.getFluidStack("molten.wurmblacksteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlueSteelIngot), FluidRegistry.getFluidStack("molten.wurmbluesteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlueSteelIngot2x), FluidRegistry.getFluidStack("molten.wurmbluesteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlueSteelSheet), FluidRegistry.getFluidStack("molten.wurmbluesteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.BlueSteelSheet2x), FluidRegistry.getFluidStack("molten.wurmbluesteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RedSteelIngot), FluidRegistry.getFluidStack("molten.wurmredsteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RedSteelIngot2x), FluidRegistry.getFluidStack("molten.wurmredsteel", 2000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RedSteelSheet), FluidRegistry.getFluidStack("molten.wurmredsteel", 1000));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.RedSteelSheet2x), FluidRegistry.getFluidStack("molten.wurmredsteel", 2000));
		TERecipes.addCrucibleRecipe(5000,new ItemStack(TFCItems.OreChunk,1,0),FluidRegistry.getFluidStack("molten.wurmcopper", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,35),FluidRegistry.getFluidStack("molten.wurmcopper", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,49),FluidRegistry.getFluidStack("molten.wurmcopper", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,1),FluidRegistry.getFluidStack("molten.wurmgold", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,36),FluidRegistry.getFluidStack("molten.wurmgold", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,50),FluidRegistry.getFluidStack("molten.wurmgold", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,2),FluidRegistry.getFluidStack("molten.wurmplatinum", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,37),FluidRegistry.getFluidStack("molten.wurmplatinum", 350));;
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,51),FluidRegistry.getFluidStack("molten.wurmplatinum", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,3),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,38),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,52),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,4),FluidRegistry.getFluidStack("molten.wurmgold", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,39),FluidRegistry.getFluidStack("molten.wurmgold", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,53),FluidRegistry.getFluidStack("molten.wurmgold", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,5),FluidRegistry.getFluidStack("molten.wurmtin", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,40),FluidRegistry.getFluidStack("molten.wurmtin", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,54),FluidRegistry.getFluidStack("molten.wurmtin", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,6),FluidRegistry.getFluidStack("molten.wurmlead", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,41),FluidRegistry.getFluidStack("molten.wurmlead", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,55),FluidRegistry.getFluidStack("molten.wurmlead", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,7),FluidRegistry.getFluidStack("molten.wurmbismuth", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,42),FluidRegistry.getFluidStack("molten.wurmbismuth", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,56),FluidRegistry.getFluidStack("molten.wurmbismuth", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,8),FluidRegistry.getFluidStack("molten.wurmnickel", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,43),FluidRegistry.getFluidStack("molten.wurmnickel", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,57),FluidRegistry.getFluidStack("molten.wurmnickel", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,9),FluidRegistry.getFluidStack("molten.wurmcopper", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,44),FluidRegistry.getFluidStack("molten.wurmcopper", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,58),FluidRegistry.getFluidStack("molten.wurmcopper", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,10),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,45),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,59),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,11),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,46),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,60),FluidRegistry.getFluidStack("molten.wurmwroughtiron", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,12),FluidRegistry.getFluidStack("molten.wurmzinc", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,4),FluidRegistry.getFluidStack("molten.wurmzinc", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,61),FluidRegistry.getFluidStack("molten.wurmzinc", 150));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,13),FluidRegistry.getFluidStack("molten.wurmcopper", 250));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,48),FluidRegistry.getFluidStack("molten.wurmcopper", 350));
		TERecipes.addCrucibleRecipe(5000, new ItemStack(TFCItems.OreChunk,1,62),FluidRegistry.getFluidStack("molten.wurmcopper", 150));
		
	}
}
