package tweaks.wurm.items;

import net.minecraft.item.EnumRarity;
import net.minecraft.item.Item;
import cpw.mods.fml.common.registry.GameRegistry;

public class ModItems {
	
	 // Custom Items
	 public static Item RedAlloyIngot;
	 public static Item RedAlloySheet;
	 public static Item QuantumSingularity;
	 public static Item MixedSheet;
	 public static Item QuarryCore;
	 public static Item WurmMold;
	 
	 // Credits
	 public static Item aCred_bismuth;
	 public static Item bCred_bismuth;
	 public static Item cCred_bismuth;
	 public static Item aCred_tin;
	 public static Item bCred_tin;
	 public static Item cCred_tin;
	 public static Item aCred_nickel;
	 public static Item bCred_nickel;
	 public static Item cCred_nickel;
	 public static Item aCred_iron;
	 public static Item bCred_iron;
	 public static Item cCred_iron;
	 public static Item aCred_copper;
	 public static Item bCred_copper;
	 public static Item cCred_copper;
	 public static Item aCred_gold;
	 public static Item bCred_gold;
	 public static Item cCred_gold;
	 public static Item aCred_silver;
	 public static Item bCred_silver;
	 public static Item cCred_silver;
	 public static Item aCred_zinc;
	 public static Item bCred_zinc;
	 public static Item cCred_zinc;
	 public static Item aCred_lead;
	 public static Item bCred_lead;
	 public static Item cCred_lead;
	 public static Item aCred_platinum;
	 public static Item bCred_platinum;
	 public static Item cCred_platinum;
	 
	 
	 // Unshaped Ingots WurmCast
	 public static Item BismuthUnshaped;
	 public static Item BismuthBronzeUnshaped;
	 public static Item BlackBronzeUnshaped;
	 public static Item BlackSteelUnshaped;
	 public static Item HCBlackSteelUnshaped;
	 public static Item BlueSteelUnshaped;
	 public static Item WeakBlueSteelUnshaped;
	 public static Item HCBlueSteelUnshaped;
	 public static Item BrassUnshaped;
	 public static Item BronzeUnshaped;
	 public static Item CopperUnshaped;
	 public static Item GoldUnshaped;
	 public static Item WroughtIronUnshaped;
	 public static Item LeadUnshaped;
	 public static Item NickelUnshaped;
	 public static Item PigIronUnshaped;
	 public static Item PlatinumUnshaped;
	 public static Item RedSteelUnshaped;
	 public static Item WeakRedSteelUnshaped;
	 public static Item HCRedSteelUnshaped;
	 public static Item RoseGoldUnshaped;
	 public static Item SilverUnshaped;
	 public static Item SteelUnshaped;
	 public static Item WeakSteelUnshaped;
	 public static Item HCSteelUnshaped;
	 public static Item SterlingSilverUnshaped;
	 public static Item TinUnshaped;
	 public static Item ZincUnshaped;
	 
	 public static Item ElectroMagneticShielding;
	 public static Item ElectroShielding;
	 public static Item Hafmium;
	 public static Item Zircon;
	 public static Item ZirconDust;
	 public static Item Titanium;
	 public static Item Francium;
	 public static Item Paladium;
	 public static Item HTHP_Diamond;
	 public static Item LeadPallet;
	 public static Item AntiMatter;
	 public static Item UnstableMatter;
	 public static Item ElectroMagneticField;
	 public static Item ContaintedAntiMatter;
	 public static Item CompressedEnergy;
	 public static Item CompressedEnergy2x;
	 
	 public static Item Tier8Engine;
	 public static Item Tier8Boster;
	 public static Item Tier8Fin;
	 
	 public static Item CraftingCore;
	 public static Item AutoCore;
	 
	 public static void register() {
		 
		 aCred_bismuth = new WurmItem().setUnlocalizedName("30cred_bismuth").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_bismuth = new WurmItem().setUnlocalizedName("50cred_bismuth").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_bismuth = new WurmItem().setUnlocalizedName("70cred_bismuth").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_tin = new WurmItem().setUnlocalizedName("30cred_tin").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_tin = new WurmItem().setUnlocalizedName("50cred_tin").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_tin = new WurmItem().setUnlocalizedName("70cred_tin").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_nickel = new WurmItem().setUnlocalizedName("30cred_nickel").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_nickel = new WurmItem().setUnlocalizedName("50cred_nickel").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_nickel = new WurmItem().setUnlocalizedName("70cred_nickel").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_iron = new WurmItem().setUnlocalizedName("30cred_iron").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_iron = new WurmItem().setUnlocalizedName("50cred_iron").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_iron = new WurmItem().setUnlocalizedName("70cred_iron").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_copper = new WurmItem().setUnlocalizedName("30cred_copper").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_copper = new WurmItem().setUnlocalizedName("50cred_copper").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_copper = new WurmItem().setUnlocalizedName("70cred_copper").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_gold = new WurmItem().setUnlocalizedName("30cred_gold").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_gold = new WurmItem().setUnlocalizedName("50cred_gold").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_gold = new WurmItem().setUnlocalizedName("70cred_gold").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_silver = new WurmItem().setUnlocalizedName("30cred_silver").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_silver = new WurmItem().setUnlocalizedName("50cred_silver").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_silver = new WurmItem().setUnlocalizedName("70cred_silver").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_zinc = new WurmItem().setUnlocalizedName("30cred_zinc").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_zinc = new WurmItem().setUnlocalizedName("50cred_zinc").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_zinc = new WurmItem().setUnlocalizedName("70cred_zinc").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_lead = new WurmItem().setUnlocalizedName("30cred_lead").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_lead = new WurmItem().setUnlocalizedName("50cred_lead").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_lead = new WurmItem().setUnlocalizedName("70cred_lead").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 aCred_platinum = new WurmItem().setUnlocalizedName("30cred_platinum").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "30_credits");
		 bCred_platinum = new WurmItem().setUnlocalizedName("50cred_platinum").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "50_credits");
		 cCred_platinum = new WurmItem().setUnlocalizedName("70cred_platinum").setMaxStackSize(16).setTextureName("wurmtweaks"+ ":" + "70_credits");
		 BismuthUnshaped = new WurmItem().setUnlocalizedName("Bismuth Unshaped").setTextureName("wurmtweaks:" + "Bismuth_Unshaped");
		 BismuthBronzeUnshaped = new WurmItem().setUnlocalizedName("Bismuth Bronze Unshaped").setTextureName("wurmtweaks:" + "Bismuth_Bronze_Unshaped");
		 BlackBronzeUnshaped = new WurmItem().setUnlocalizedName("Black Bronze Unshaped").setTextureName("wurmtweaks:" + "Black_Bronze_Unshaped");
		 BlackSteelUnshaped = new WurmItem().setUnlocalizedName("Black Steel Unshaped").setTextureName("wurmtweaks:" + "Black_Steel_Unshaped");
		 BlueSteelUnshaped = new WurmItem().setUnlocalizedName("Blue Steel Unshaped").setTextureName("wurmtweaks:" + "Blue_Steel_Unshaped");
		 BrassUnshaped = new WurmItem().setUnlocalizedName("Brass Unshaped").setTextureName("wurmtweaks:" + "Brass_Unshaped");
		 BronzeUnshaped = new WurmItem().setUnlocalizedName("Bronze Unshaped").setTextureName("wurmtweaks:" + "Bronze_Unshaped");
		 CopperUnshaped = new WurmItem().setUnlocalizedName("Copper Unshaped").setTextureName("wurmtweaks:" + "Copper_Unshaped");
		 GoldUnshaped = new WurmItem().setUnlocalizedName("Gold Unshaped").setTextureName("wurmtweaks:" + "Gold_Unshaped");
		 WroughtIronUnshaped = new WurmItem().setUnlocalizedName("Wrought Iron Unshaped").setTextureName("wurmtweaks:" + "Wrought_Iron_Unshaped");
		 LeadUnshaped = new WurmItem().setUnlocalizedName("Lead Unshaped").setTextureName("wurmtweaks:" + "Lead_Unshaped");
		 NickelUnshaped = new WurmItem().setUnlocalizedName("Nickel Unshaped").setTextureName("wurmtweaks:" + "Nickel_Unshaped");
		 PigIronUnshaped = new WurmItem().setUnlocalizedName("Pig Iron Unshaped").setTextureName("wurmtweaks:" + "Pig_Iron_Unshaped");
		 PlatinumUnshaped = new WurmItem().setUnlocalizedName("Platinum Unshaped").setTextureName("wurmtweaks:" + "Platinum_Unshaped");
		 RedSteelUnshaped = new WurmItem().setUnlocalizedName("Red Steel Unshaped").setTextureName("wurmtweaks:" + "Red_Steel_Unshaped");
		 RoseGoldUnshaped = new WurmItem().setUnlocalizedName("Rose Gold Unshaped").setTextureName("wurmtweaks:" + "Rose_Gold_Unshaped");
		 SilverUnshaped = new WurmItem().setUnlocalizedName("Silver Unshaped").setTextureName("wurmtweaks:" + "Silver_Unshaped");
		 SteelUnshaped = new WurmItem().setUnlocalizedName("Steel Unshaped").setTextureName("wurmtweaks:" + "Steel_Unshaped");
		 SterlingSilverUnshaped = new WurmItem().setUnlocalizedName("Sterling Silver Unshaped").setTextureName("wurmtweaks:" + "Sterling_Silver_Unshaped");
		 TinUnshaped = new WurmItem().setUnlocalizedName("Tin Unshaped").setTextureName("wurmtweaks:" + "Tin_Unshaped");
		 ZincUnshaped = new WurmItem().setUnlocalizedName("Zinc Unshaped").setTextureName("wurmtweaks:" + "Zinc_Unshaped");
		 WurmMold = new WurmMold().setUnlocalizedName("wurmMold").setMaxStackSize(4).setTextureName("wurmtweaks" + ":" + "wurmMold");
		 RedAlloySheet = new WurmItem().setUnlocalizedName("RedAlloySheet").setMaxStackSize(32).setTextureName("wurmtweaks" + ":" + "RedAlloySheet");
		 RedAlloyIngot = new WurmItem().setUnlocalizedName("RedAlloyIngot").setMaxStackSize(32).setTextureName("wurmtweaks" + ":" + "RedAlloyIngot");
		 QuantumSingularity = new WurmItem().setUnlocalizedName("QuantumSingularity").setMaxStackSize(4).setTextureName("wurmtweaks" + ":" + "QuantumSingularity");
		 MixedSheet = new WurmItem().setUnlocalizedName("MixedSheet").setMaxStackSize(32).setTextureName("wurmtweaks" + ":" + "MixedSheet");
		 QuarryCore = new WurmItem().setUnlocalizedName("QuarryCore").setMaxStackSize(1).setTextureName("wurmtweaks"+ ":" + "QuarryCore");
		
		 ElectroMagneticShielding = new WurmCItem(false, EnumRarity.rare).setUnlocalizedName("ElectroMagneticShielding").setMaxStackSize(4).setTextureName("wurmtweaks:" + "ElectroMagneticShielding");
		 ElectroShielding = new WurmCItem(false,EnumRarity.uncommon).setUnlocalizedName("ElectroShielding").setMaxStackSize(8).setTextureName("wurmtweaks:"+ "ElectroShielding");
		 Hafmium = new WurmItem().setUnlocalizedName("Hafmium").setMaxStackSize(16).setTextureName("wurmtweaks:"+ "Hafmium");
		 Zircon = new WurmItem().setUnlocalizedName("Zircon").setMaxStackSize(16).setTextureName("wurmtweaks:" + "Zircon");
		 ZirconDust = new WurmItem().setUnlocalizedName("Zircon_Dust").setMaxStackSize(32).setTextureName("wurmtweaks:" + "ZirconDust");
		 Titanium = new WurmCItem(false,EnumRarity.uncommon).setUnlocalizedName("Titanium").setMaxStackSize(32).setTextureName("wurmtweaks:"+ "Titanium");
		 Francium = new WurmItem().setUnlocalizedName("Francium").setMaxStackSize(32).setTextureName("wurmtweaks:"+ "Francium");
		 Paladium = new WurmItem().setUnlocalizedName("Paladium").setMaxStackSize(32).setTextureName("wurmtweaks:"+ "Paladium");
		 HTHP_Diamond = new WurmCItem(true,EnumRarity.common).setMaxStackSize(4).setUnlocalizedName("HTHP_Diamond").setTextureName("wurmtweaks:"+ "HTHP_Diamond");
		 LeadPallet = new WurmItem().setMaxStackSize(5).setUnlocalizedName("LeadPallet").setTextureName("wurmtweaks:"+"LeadPallet");
		 UnstableMatter = new UnstableMatter().setMaxStackSize(2).setUnlocalizedName("UnstableMatter").setTextureName("wurmtweaks:"+ "UnstableMatter");
		 AntiMatter = new AntiMatter().setMaxStackSize(4).setUnlocalizedName("AntiMatter").setTextureName("wurmtweaks:"+"AntiMatter");
		 ElectroMagneticField = new WurmCItem(false,EnumRarity.rare).setMaxStackSize(8).setUnlocalizedName("ElectroMagneticField").setTextureName("wurmtweaks:" + "ElectroMagneticField");
		 ContaintedAntiMatter = new WurmCItem(true,EnumRarity.epic).setMaxStackSize(1).setUnlocalizedName("ContaintedAntiMatter").setTextureName("wurmtweaks:"+ "ContaintedAntiMatter");
		 CompressedEnergy = new WurmCItem(false,EnumRarity.epic).setUnlocalizedName("CompressedEnergy").setTextureName("wurmtweaks:" + "CompressedEnergy");
		 CompressedEnergy2x = new WurmCItem(false,EnumRarity.epic).setUnlocalizedName("CompressedEnergy2x").setTextureName("wurmtweaks:" + "CompressedEnergy2x");
		 Tier8Engine = new WurmCItem(false, EnumRarity.rare).setUnlocalizedName("Tier8Engine").setTextureName("wurmtweaks:" + "Tier8Engine").setMaxStackSize(1);
		 Tier8Boster = new WurmItem().setUnlocalizedName("Tier8Boster").setTextureName("wurmtweaks:" + "Tier8Boster").setMaxStackSize(4);
		 Tier8Fin = new WurmItem().setUnlocalizedName("Tier8Fin").setTextureName("wurmtweaks:" + "Tier8Fin");
		 CraftingCore = new WurmItem().setUnlocalizedName("CraftingCore").setTextureName("wurmtweaks:" + "craftingcore").setMaxStackSize(16);
		 AutoCore = new WurmItem().setUnlocalizedName("AutoCore").setTextureName("wurmtweaks:"+ "autocore");
		 
		 GameRegistry.registerItem(RedAlloySheet, RedAlloySheet.getUnlocalizedName());
		 GameRegistry.registerItem(RedAlloyIngot, RedAlloyIngot.getUnlocalizedName());
		 GameRegistry.registerItem(QuantumSingularity, QuantumSingularity.getUnlocalizedName());
		 GameRegistry.registerItem(MixedSheet, MixedSheet.getUnlocalizedName());
		 GameRegistry.registerItem(QuarryCore, QuarryCore.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_bismuth, aCred_bismuth.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_bismuth, bCred_bismuth.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_bismuth, cCred_bismuth.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_tin, aCred_tin.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_tin, bCred_tin.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_tin, cCred_tin.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_nickel, aCred_nickel.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_nickel, bCred_nickel.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_nickel, cCred_nickel.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_iron, aCred_iron.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_iron, bCred_iron.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_iron, cCred_iron.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_copper, aCred_copper.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_copper, bCred_copper.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_copper, cCred_copper.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_copper, aCred_copper.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_copper, bCred_copper.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_copper, cCred_copper.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_gold, aCred_gold.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_gold, bCred_gold.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_gold, cCred_gold.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_silver, aCred_silver.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_silver, bCred_silver.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_silver, cCred_silver.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_zinc, aCred_zinc.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_zinc, bCred_zinc.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_zinc, cCred_zinc.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_lead, aCred_lead.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_lead, bCred_lead.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_lead, cCred_lead.getUnlocalizedName());
		 GameRegistry.registerItem(aCred_platinum, aCred_platinum.getUnlocalizedName());
		 GameRegistry.registerItem(bCred_platinum, bCred_platinum.getUnlocalizedName());
		 GameRegistry.registerItem(cCred_platinum, cCred_platinum.getUnlocalizedName());
		 GameRegistry.registerItem(WurmMold, WurmMold.getUnlocalizedName());
		 GameRegistry.registerItem(BismuthUnshaped, BismuthUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(BismuthBronzeUnshaped, BismuthBronzeUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(BlackBronzeUnshaped, BlackBronzeUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(BlackSteelUnshaped, BlackSteelUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(BlueSteelUnshaped, BlueSteelUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(BrassUnshaped, BrassUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(BronzeUnshaped, BronzeUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(CopperUnshaped, CopperUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(GoldUnshaped, GoldUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(WroughtIronUnshaped, WroughtIronUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(LeadUnshaped, LeadUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(NickelUnshaped, NickelUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(PigIronUnshaped, PigIronUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(PlatinumUnshaped, PlatinumUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(RedSteelUnshaped, RedSteelUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(RoseGoldUnshaped, RoseGoldUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(SilverUnshaped, SilverUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(SteelUnshaped, SteelUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(SterlingSilverUnshaped, SterlingSilverUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(TinUnshaped, TinUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(ZincUnshaped, ZincUnshaped.getUnlocalizedName());
		 GameRegistry.registerItem(ElectroMagneticShielding,ElectroMagneticShielding.getUnlocalizedName());
		 GameRegistry.registerItem(ElectroShielding, ElectroShielding.getUnlocalizedName());
		 GameRegistry.registerItem(Hafmium, Hafmium.getUnlocalizedName());
		 GameRegistry.registerItem(Zircon, Zircon.getUnlocalizedName());
		 GameRegistry.registerItem(ZirconDust, ZirconDust.getUnlocalizedName());
		 GameRegistry.registerItem(Titanium, Titanium.getUnlocalizedName());
		 GameRegistry.registerItem(Francium, Francium.getUnlocalizedName());
		 GameRegistry.registerItem(Paladium,Paladium.getUnlocalizedName());
		 GameRegistry.registerItem(HTHP_Diamond, HTHP_Diamond.getUnlocalizedName());
		 GameRegistry.registerItem(LeadPallet, LeadPallet.getUnlocalizedName());
		 GameRegistry.registerItem(AntiMatter, AntiMatter.getUnlocalizedName());
		 GameRegistry.registerItem(UnstableMatter,UnstableMatter.getUnlocalizedName());
		 GameRegistry.registerItem(ElectroMagneticField, ElectroMagneticField.getUnlocalizedName());
		 GameRegistry.registerItem(ContaintedAntiMatter, ContaintedAntiMatter.getUnlocalizedName());
		 GameRegistry.registerItem(CompressedEnergy, CompressedEnergy.getUnlocalizedName());
		 GameRegistry.registerItem(CompressedEnergy2x, CompressedEnergy2x.getUnlocalizedName());
		 GameRegistry.registerItem(Tier8Engine, Tier8Engine.getUnlocalizedName());
		 GameRegistry.registerItem(Tier8Boster, Tier8Boster.getUnlocalizedName());
		 GameRegistry.registerItem(Tier8Fin, Tier8Fin.getUnlocalizedName());
		 GameRegistry.registerItem(CraftingCore, CraftingCore.getUnlocalizedName());
		 GameRegistry.registerItem(AutoCore, AutoCore.getUnlocalizedName());
	 }
}
